-- V010: 创建建议表（独立于message表，支持进度追踪）
CREATE TABLE IF NOT EXISTS suggestion (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT DEFAULT NULL COMMENT '提交用户ID',
    suggest_no VARCHAR(32) NOT NULL COMMENT '建议单号',
    title VARCHAR(100) NOT NULL COMMENT '建议标题',
    type VARCHAR(20) DEFAULT '网站建议' COMMENT '建议类型: 网站建议/部门建议/我要纠错/助企惠企服务专区建议',
    real_name VARCHAR(50) NOT NULL COMMENT '建议人姓名',
    id_card VARCHAR(20) DEFAULT NULL COMMENT '身份证号',
    email VARCHAR(100) DEFAULT NULL COMMENT '电子邮箱',
    phone VARCHAR(20) NOT NULL COMMENT '联系电话',
    address VARCHAR(200) DEFAULT NULL COMMENT '联系地址',
    province VARCHAR(50) DEFAULT NULL COMMENT '省份',
    city VARCHAR(50) DEFAULT NULL COMMENT '城市',
    district VARCHAR(50) DEFAULT NULL COMMENT '区县',
    detail_address VARCHAR(100) DEFAULT NULL COMMENT '具体地址',
    content TEXT NOT NULL COMMENT '建议内容',
    is_public TINYINT(1) DEFAULT 1 COMMENT '是否公开: 1-是, 0-否',
    is_secret TINYINT(1) DEFAULT 0 COMMENT '是否保密: 1-是, 0-否',
    status VARCHAR(20) DEFAULT '待受理' COMMENT '状态: 待受理/处理中/已答复/已办结',
    reply_content TEXT DEFAULT NULL COMMENT '答复内容',
    reply_by VARCHAR(50) DEFAULT NULL COMMENT '答复人',
    reply_time DATETIME DEFAULT NULL COMMENT '答复时间',
    deadline DATE DEFAULT NULL COMMENT '答复期限',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT DEFAULT NULL COMMENT '创建人',
    update_by BIGINT DEFAULT NULL COMMENT '更新人',
    deleted INT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0-未删除,1-已删除',
    UNIQUE INDEX idx_suggest_no (suggest_no),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='建议表';
